steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker build --build-arg ENV_FILE=.env -t gcr.io/${PROJECT_ID}/${_SERVICE_NAME} . ",
      ]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]

  - id: "run deploy"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--platform",
        "managed",
        "--region",
        "${_REGION}",
        "--image",
        "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}",
        "--port",
        "${_PORT}",
        "--allow-unauthenticated",
      ]

substitutions:
  _REGION: asia-southeast1
  _SERVICE_NAME: kampung-frontend
  _PORT: "80"

images:
  - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"
